import matplotlib.pyplot as plt
plt.style.use('dark_background')
fig, ax = plt.subplots(figsize=(5,5))
ax.quiver(0, 0, 2, 3, angles='xy', scale_units='xy', scale=1, color='lime', label=r'$\vec{v}$')
ax.text(2.1, 3, r"$\vec{v} = 2i + 3j$", color='lime', fontsize=14)
ax.set_xlim(0, 4)
ax.set_ylim(0, 4)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_aspect('equal')
ax.set_title('Single Vector')
plt.grid(True, alpha=0.2)
plt.legend()
plt.savefig('/Users/nana-kojobanafo/Documents/Physics Website/images/Maths For Physicists/Single_Vector.png')
plt.close(fig)
